In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df_p = pd.read_csv("./results/SynthBase_params.csv",compression="gzip")
df_r = pd.read_csv("./results/SynthBase_results.csv",compression="gzip")
df_all = pd.merge(df_p, df_r, on=["trial","experiment_timestamp"])

In [13]:
u = df_all.groupby(["fs_name","forecaster_name","data_name"])[['fs_size']].mean().reset_index()
print("number of MTS evaluated by fs and es algo")
u.groupby(["fs_name","forecaster_name"])["fs_size"].count()

number of MTS evaluated by fs and es algo

fs_name              forecaster_name
CausalPairs          LinearDartsWrapper    5
NoSelection          LinearDartsWrapper    5
SingleChronoEpilogi  LinearDartsWrapper    5
Name: fs_size, dtype: int64

In [15]:
print("Average performances over configuration and MTS, during tuning, for each fs and es algo")
df_all.groupby(["fs_name","forecaster_name"])[['fs_size', 'eq-tp',
       'eq-fp', 'eq-fn', 'eq-precision', 'eq-recall', 'eq-f1', 'fs_time',
       'forecaster.training_time', 'forecaster.predict_time', 'mfe', 'mae',
       'rmse', 'r2', 'mape', 'smape', 'mase']].mean()

Average performances over configuration and MTS, during tuning, for each fs and es algo

,,fs_size,eq-tp,eq-fp,eq-fn,eq-precision,eq-recall,eq-f1,fs_time,forecaster.training_time,forecaster.predict_time,mfe,mae,rmse,r2,mape,smape,mase
fs_name,forecaster_name,,,,,,,,,,,,,,,,,
CausalPairs,LinearDartsWrapper,5.729333,2.706667,3.022667,8.293333,0.643714,0.246061,0.313560,1.783568e-01,0.023467,0.062931,-0.008176,0.960131,1.206123,0.141367,556.149830,137.165362,0.660915
NoSelection,LinearDartsWrapper,101.000000,11.000000,90.000000,0.000000,0.108911,1.000000,0.196429,5.219777e-07,1.066383,0.097125,-0.004706,0.867655,1.089546,0.284922,474.514782,115.175647,0.600904
SingleChronoEpilogi,LinearDartsWrapper,9.936000,9.132000,0.804000,1.868000,0.941232,0.830182,0.846868,6.211477e-01,0.052312,0.066493,-0.006094,0.829586,1.039923,0.349584,550.512324,116.827612,0.573872

In [18]:
print("Average performances over MTS, for the best configuration each, during tuning, for each fs and es algo")
idx = df_all.groupby(["fs_name","forecaster_name","data_name"])['r2'].transform(max) == df_all['r2']
u=df_all[idx].groupby(["fs_name","data_name","forecaster_name"]).first().reset_index()
u.groupby(["fs_name","forecaster_name"])[['fs_size', 'eq-tp',
       'eq-fp', 'eq-fn', 'eq-precision', 'eq-recall', 'eq-f1', 'fs_time',
       'forecaster.training_time', 'forecaster.predict_time', 'mfe', 'mae',
       'rmse', 'r2', 'mape', 'smape', 'mase']].mean()

Average performances over MTS, for the best configuration each, during tuning, for each fs and es algo

C:\Users\Vassilis\AppData\Local\Temp\ipykernel_24048\4281486445.py:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  idx = df_all.groupby(["fs_name","forecaster_name","data_name"])['r2'].transform(max) == df_all['r2']

,,fs_size,eq-tp,eq-fp,eq-fn,eq-precision,eq-recall,eq-f1,fs_time,forecaster.training_time,forecaster.predict_time,mfe,mae,rmse,r2,mape,smape,mase
fs_name,forecaster_name,,,,,,,,,,,,,,,,,
CausalPairs,LinearDartsWrapper,6.6,3.4,3.2,7.6,0.616941,0.309091,0.378708,1.480746e-01,0.025001,0.070541,-0.008002,0.941963,1.183856,0.171704,526.057461,133.348166,0.648917
NoSelection,LinearDartsWrapper,101.0,11.0,90.0,0.0,0.108911,1.000000,0.196429,6.675720e-07,0.959895,0.124966,-0.004706,0.867655,1.089546,0.284922,474.514782,115.175647,0.600904
SingleChronoEpilogi,LinearDartsWrapper,10.8,10.8,0.0,0.2,1.000000,0.981818,0.990476,7.819468e+00,0.052440,0.062743,-0.006136,0.803132,1.006947,0.389994,535.273645,112.878011,0.556143

In [22]:
print("Performance, For each MTS, for the best configuration each, during tuning, for each fs and es algo")
idx = df_all.groupby(["fs_name","forecaster_name","data_name"])['r2'].transform(max) == df_all['r2']
df_all[idx].groupby(["data_name","fs_name","forecaster_name"]).first()[['fs_size', 'eq-tp',
       'eq-fp', 'eq-fn', 'eq-precision', 'eq-recall', 'eq-f1', 'fs_time',
       'forecaster.training_time', 'forecaster.predict_time', 'mfe', 'mae',
       'rmse', 'r2', 'mape', 'smape', 'mase']]

Performance, For each MTS, for the best configuration each, during tuning, for each fs and es algo

C:\Users\Vassilis\AppData\Local\Temp\ipykernel_24048\3201953548.py:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  idx = df_all.groupby(["fs_name","forecaster_name","data_name"])['r2'].transform(max) == df_all['r2']

                                                                      fs_size  \
data_name                  fs_name             forecaster_name
SynthBase,ip0.0repetition0 CausalPairs         LinearDartsWrapper    9.333333
                           NoSelection         LinearDartsWrapper  101.000000
                           SingleChronoEpilogi LinearDartsWrapper   11.000000
SynthBase,ip0.0repetition1 CausalPairs         LinearDartsWrapper    6.333333
                           NoSelection         LinearDartsWrapper  101.000000
                           SingleChronoEpilogi LinearDartsWrapper   11.000000
SynthBase,ip0.2repetition0 CausalPairs         LinearDartsWrapper    1.666667
                           NoSelection         LinearDartsWrapper  101.000000
                           SingleChronoEpilogi LinearDartsWrapper   11.000000
SynthBase,ip0.2repetition1 CausalPairs         LinearDartsWrapper    7.666667
                           NoSelection         LinearDartsWrapper  101.000000
                           SingleChronoEpilogi LinearDartsWrapper   11.000000
SynthBase,ip0.4repetition0 CausalPairs         LinearDartsWrapper    8.000000
                           NoSelection         LinearDartsWrapper  101.000000
                           SingleChronoEpilogi LinearDartsWrapper   10.000000

                                                                       eq-tp  \
data_name                  fs_name             forecaster_name
SynthBase,ip0.0repetition0 CausalPairs         LinearDartsWrapper   3.333333
                           NoSelection         LinearDartsWrapper  11.000000
                           SingleChronoEpilogi LinearDartsWrapper  11.000000
SynthBase,ip0.0repetition1 CausalPairs         LinearDartsWrapper   3.666667
                           NoSelection         LinearDartsWrapper  11.000000
                           SingleChronoEpilogi LinearDartsWrapper  11.000000
SynthBase,ip0.2repetition0 CausalPairs         LinearDartsWrapper   1.666667
                           NoSelection         LinearDartsWrapper  11.000000
                           SingleChronoEpilogi LinearDartsWrapper  11.000000
SynthBase,ip0.2repetition1 CausalPairs         LinearDartsWrapper   3.333333
                           NoSelection         LinearDartsWrapper  11.000000
                           SingleChronoEpilogi LinearDartsWrapper  11.000000
SynthBase,ip0.4repetition0 CausalPairs         LinearDartsWrapper   5.000000
                           NoSelection         LinearDartsWrapper  11.000000
                           SingleChronoEpilogi LinearDartsWrapper  10.000000

                                                                       eq-fp  \
data_name                  fs_name             forecaster_name
SynthBase,ip0.0repetition0 CausalPairs         LinearDartsWrapper   6.000000
                           NoSelection         LinearDartsWrapper  90.000000
                           SingleChronoEpilogi LinearDartsWrapper   0.000000
SynthBase,ip0.0repetition1 CausalPairs         LinearDartsWrapper   2.666667
                           NoSelection         LinearDartsWrapper  90.000000
                           SingleChronoEpilogi LinearDartsWrapper   0.000000
SynthBase,ip0.2repetition0 CausalPairs         LinearDartsWrapper   0.000000
                           NoSelection         LinearDartsWrapper  90.000000
                           SingleChronoEpilogi LinearDartsWrapper   0.000000
SynthBase,ip0.2repetition1 CausalPairs         LinearDartsWrapper   4.333333
                           NoSelection         LinearDartsWrapper  90.000000
                           SingleChronoEpilogi LinearDartsWrapper   0.000000
SynthBase,ip0.4repetition0 CausalPairs         LinearDartsWrapper   3.000000
                           NoSelection         LinearDartsWrapper  90.000000
                           SingleChronoEpilogi LinearDartsWrapper   0.000000

                                                                      eq-fn  \
data_name                  fs_name             forecaster_name
SynthBase,ip0.0repetition0 CausalPairs         LinearDartsWrapper  7.666667
                           NoSelection         LinearDartsWrapper  0.000000
                           SingleChronoEpilogi LinearDartsWrapper  0.000000
SynthBase,ip0.0repetition1 CausalPairs         LinearDartsWrapper  7.333333
                           NoSelection         LinearDartsWrapper  0.000000
                           SingleChronoEpilogi LinearDartsWrapper  0.000000
SynthBase,ip0.2repetition0 CausalPairs         LinearDartsWrapper  9.333333
                           NoSelection         LinearDartsWrapper  0.000000
                           SingleChronoEpilogi LinearDartsWrapper  0.000000
SynthBase,ip0.2repetition1 CausalPairs         LinearDartsWrapper  7.666667
                           NoSelection         LinearDartsWrapper  0.000000
                           SingleChronoEpilogi LinearDartsWrapper  0.000000
SynthBase,ip0.4repetition0 CausalPairs         LinearDartsWrapper  6.000000
                           NoSelection         LinearDartsWrapper  0.000000
                           SingleChronoEpilogi LinearDartsWrapper  1.000000

                                                                   eq-precision  \
data_name                  fs_name             forecaster_name
SynthBase,ip0.0repetition0 CausalPairs         LinearDartsWrapper      0.402564
                           NoSelection         LinearDartsWrapper      0.108911
                           SingleChronoEpilogi LinearDartsWrapper      1.000000
SynthBase,ip0.0repetition1 CausalPairs         LinearDartsWrapper      0.588889
                           NoSelection         LinearDartsWrapper      0.108911
                           SingleChronoEpilogi LinearDartsWrapper      1.000000
SynthBase,ip0.2repetition0 CausalPairs         LinearDartsWrapper      1.000000
                           NoSelection         LinearDartsWrapper      0.108911
                           SingleChronoEpilogi LinearDartsWrapper      1.000000
SynthBase,ip0.2repetition1 CausalPairs         LinearDartsWrapper      0.468254
                           NoSelection         LinearDartsWrapper      0.108911
                           SingleChronoEpilogi LinearDartsWrapper      1.000000
SynthBase,ip0.4repetition0 CausalPairs         LinearDartsWrapper      0.625000
                           NoSelection         LinearDartsWrapper      0.108911
                           SingleChronoEpilogi LinearDartsWrapper      1.000000

                                                                   eq-recall  \
data_name                  fs_name             forecaster_name
SynthBase,ip0.0repetition0 CausalPairs         LinearDartsWrapper   0.303030
                           NoSelection         LinearDartsWrapper   1.000000
                           SingleChronoEpilogi LinearDartsWrapper   1.000000
SynthBase,ip0.0repetition1 CausalPairs         LinearDartsWrapper   0.333333
                           NoSelection         LinearDartsWrapper   1.000000
                           SingleChronoEpilogi LinearDartsWrapper   1.000000
SynthBase,ip0.2repetition0 CausalPairs         LinearDartsWrapper   0.151515
                           NoSelection         LinearDartsWrapper   1.000000
                           SingleChronoEpilogi LinearDartsWrapper   1.000000
SynthBase,ip0.2repetition1 CausalPairs         LinearDartsWrapper   0.303030
                           NoSelection         LinearDartsWrapper   1.000000
                           SingleChronoEpilogi LinearDartsWrapper   1.000000
SynthBase,ip0.4repetition0 CausalPairs         LinearDartsWrapper   0.454545
                           NoSelection         LinearDartsWrapper   1.000000
                           SingleChronoEpilogi LinearDartsWrapper   0.909091

                                                                      eq-f1  \
data_name                  fs_name             forecaster_name
SynthBase,ip0.0repetition0 CausalPairs         LinearDartsWrapper  0.331349
                           NoSelection         LinearDartsWrapper  0.196429
                           SingleChronoEpilogi LinearDartsWrapper  1.000000
SynthBase,ip0.0repetition1 CausalPairs         LinearDartsWrapper  0.422214
                           NoSelection         LinearDartsWrapper  0.196429
                           SingleChronoEpilogi LinearDartsWrapper  1.000000
SynthBase,ip0.2repetition0 CausalPairs         LinearDartsWrapper  0.260684
                           NoSelection         LinearDartsWrapper  0.196429
                           SingleChronoEpilogi LinearDartsWrapper  1.000000
SynthBase,ip0.2repetition1 CausalPairs         LinearDartsWrapper  0.352979
                           NoSelection         LinearDartsWrapper  0.196429
                           SingleChronoEpilogi LinearDartsWrapper  1.000000
SynthBase,ip0.4repetition0 CausalPairs         LinearDartsWrapper  0.526316
                           NoSelection         LinearDartsWrapper  0.196429
                           SingleChronoEpilogi LinearDartsWrapper  0.952381

                                                                        fs_time  \
data_name                  fs_name             forecaster_name
SynthBase,ip0.0repetition0 CausalPairs         LinearDartsWrapper  1.545863e-01
                           NoSelection         LinearDartsWrapper  6.357829e-07
                           SingleChronoEpilogi LinearDartsWrapper  7.844023e+00
SynthBase,ip0.0repetition1 CausalPairs         LinearDartsWrapper  1.573020e-01
                           NoSelection         LinearDartsWrapper  7.152557e-07
                           SingleChronoEpilogi LinearDartsWrapper  1.164844e+01
SynthBase,ip0.2repetition0 CausalPairs         LinearDartsWrapper  1.474108e-01
                           NoSelection         LinearDartsWrapper  7.152557e-07
                           SingleChronoEpilogi LinearDartsWrapper  9.785649e+00
SynthBase,ip0.2repetition1 CausalPairs         LinearDartsWrapper  1.588972e-01
                           NoSelection         LinearDartsWrapper  6.357829e-07
                           SingleChronoEpilogi LinearDartsWrapper  9.083665e+00
SynthBase,ip0.4repetition0 CausalPairs         LinearDartsWrapper  1.221768e-01
                           NoSelection         LinearDartsWrapper  6.357829e-07
                           SingleChronoEpilogi LinearDartsWrapper  7.355610e-01

                                                                   forecaster.training_time  \
data_name                  fs_name             forecaster_name
SynthBase,ip0.0repetition0 CausalPairs         LinearDartsWrapper                  0.037226
                           NoSelection         LinearDartsWrapper                  0.847569
                           SingleChronoEpilogi LinearDartsWrapper                  0.052383
SynthBase,ip0.0repetition1 CausalPairs         LinearDartsWrapper                  0.021990
                           NoSelection         LinearDartsWrapper                  0.835041
                           SingleChronoEpilogi LinearDartsWrapper                  0.049775
SynthBase,ip0.2repetition0 CausalPairs         LinearDartsWrapper                  0.005571
                           NoSelection         LinearDartsWrapper                  0.867517
                           SingleChronoEpilogi LinearDartsWrapper                  0.050467
SynthBase,ip0.2repetition1 CausalPairs         LinearDartsWrapper                  0.032120
                           NoSelection         LinearDartsWrapper                  0.988890
                           SingleChronoEpilogi LinearDartsWrapper                  0.057470
SynthBase,ip0.4repetition0 CausalPairs         LinearDartsWrapper                  0.028099
                           NoSelection         LinearDartsWrapper                  1.260456
                           SingleChronoEpilogi LinearDartsWrapper                  0.052106

                                                                   forecaster.predict_time  \
data_name                  fs_name             forecaster_name
SynthBase,ip0.0repetition0 CausalPairs         LinearDartsWrapper                 0.058598
                           NoSelection         LinearDartsWrapper                 0.126872
                           SingleChronoEpilogi LinearDartsWrapper                 0.057920
SynthBase,ip0.0repetition1 CausalPairs         LinearDartsWrapper                 0.119484
                           NoSelection         LinearDartsWrapper                 0.122140
                           SingleChronoEpilogi LinearDartsWrapper                 0.070500
SynthBase,ip0.2repetition0 CausalPairs         LinearDartsWrapper                 0.057905
                           NoSelection         LinearDartsWrapper                 0.119842
                           SingleChronoEpilogi LinearDartsWrapper                 0.060289
SynthBase,ip0.2repetition1 CausalPairs         LinearDartsWrapper                 0.059919
                           NoSelection         LinearDartsWrapper                 0.126095
                           SingleChronoEpilogi LinearDartsWrapper                 0.063453
SynthBase,ip0.4repetition0 CausalPairs         LinearDartsWrapper                 0.056799
                           NoSelection         LinearDartsWrapper                 0.129882
                           SingleChronoEpilogi LinearDartsWrapper                 0.061552

                                                                        mfe  \
data_name                  fs_name             forecaster_name
SynthBase,ip0.0repetition0 CausalPairs         LinearDartsWrapper  0.028113
                           NoSelection         LinearDartsWrapper  0.029426
                           SingleChronoEpilogi LinearDartsWrapper  0.029969
SynthBase,ip0.0repetition1 CausalPairs         LinearDartsWrapper  0.003099
                           NoSelection         LinearDartsWrapper -0.014302
                           SingleChronoEpilogi LinearDartsWrapper -0.014424
SynthBase,ip0.2repetition0 CausalPairs         LinearDartsWrapper -0.031034
                           NoSelection         LinearDartsWrapper -0.007421
                           SingleChronoEpilogi LinearDartsWrapper -0.009124
SynthBase,ip0.2repetition1 CausalPairs         LinearDartsWrapper -0.037312
                           NoSelection         LinearDartsWrapper -0.014144
                           SingleChronoEpilogi LinearDartsWrapper -0.027843
SynthBase,ip0.4repetition0 CausalPairs         LinearDartsWrapper -0.002879
                           NoSelection         LinearDartsWrapper -0.017088
                           SingleChronoEpilogi LinearDartsWrapper -0.009258

                                                                        mae  \
data_name                  fs_name             forecaster_name
SynthBase,ip0.0repetition0 CausalPairs         LinearDartsWrapper  0.934341
                           NoSelection         LinearDartsWrapper  0.870088
                           SingleChronoEpilogi LinearDartsWrapper  0.802306
SynthBase,ip0.0repetition1 CausalPairs         LinearDartsWrapper  0.965455
                           NoSelection         LinearDartsWrapper  0.854208
                           SingleChronoEpilogi LinearDartsWrapper  0.800868
SynthBase,ip0.2repetition0 CausalPairs         LinearDartsWrapper  1.003484
                           NoSelection         LinearDartsWrapper  0.871277
                           SingleChronoEpilogi LinearDartsWrapper  0.802241
SynthBase,ip0.2repetition1 CausalPairs         LinearDartsWrapper  0.953926
                           NoSelection         LinearDartsWrapper  0.868966
                           SingleChronoEpilogi LinearDartsWrapper  0.803805
SynthBase,ip0.4repetition0 CausalPairs         LinearDartsWrapper  0.852611
                           NoSelection         LinearDartsWrapper  0.873736
                           SingleChronoEpilogi LinearDartsWrapper  0.806437

                                                                       rmse  \
data_name                  fs_name             forecaster_name
SynthBase,ip0.0repetition0 CausalPairs         LinearDartsWrapper  1.163880
                           NoSelection         LinearDartsWrapper  1.086143
                           SingleChronoEpilogi LinearDartsWrapper  1.005091
SynthBase,ip0.0repetition1 CausalPairs         LinearDartsWrapper  1.220989
                           NoSelection         LinearDartsWrapper  1.075825
                           SingleChronoEpilogi LinearDartsWrapper  1.003099
SynthBase,ip0.2repetition0 CausalPairs         LinearDartsWrapper  1.265357
                           NoSelection         LinearDartsWrapper  1.099181
                           SingleChronoEpilogi LinearDartsWrapper  1.009273
SynthBase,ip0.2repetition1 CausalPairs         LinearDartsWrapper  1.197586
                           NoSelection         LinearDartsWrapper  1.085247
                           SingleChronoEpilogi LinearDartsWrapper  1.001855
SynthBase,ip0.4repetition0 CausalPairs         LinearDartsWrapper  1.071469
                           NoSelection         LinearDartsWrapper  1.101333
                           SingleChronoEpilogi LinearDartsWrapper  1.015416

                                                                         r2  \
data_name                  fs_name             forecaster_name
SynthBase,ip0.0repetition0 CausalPairs         LinearDartsWrapper  0.116416
                           NoSelection         LinearDartsWrapper  0.230584
                           SingleChronoEpilogi LinearDartsWrapper  0.341297
SynthBase,ip0.0repetition1 CausalPairs         LinearDartsWrapper  0.297546
                           NoSelection         LinearDartsWrapper  0.451652
                           SingleChronoEpilogi LinearDartsWrapper  0.523870
SynthBase,ip0.2repetition0 CausalPairs         LinearDartsWrapper  0.163750
                           NoSelection         LinearDartsWrapper  0.367709
                           SingleChronoEpilogi LinearDartsWrapper  0.466427
SynthBase,ip0.2repetition1 CausalPairs         LinearDartsWrapper  0.168945
                           NoSelection         LinearDartsWrapper  0.313667
                           SingleChronoEpilogi LinearDartsWrapper  0.416342
SynthBase,ip0.4repetition0 CausalPairs         LinearDartsWrapper  0.111861
                           NoSelection         LinearDartsWrapper  0.060998
                           SingleChronoEpilogi LinearDartsWrapper  0.202034

                                                                          mape  \
data_name                  fs_name             forecaster_name
SynthBase,ip0.0repetition0 CausalPairs         LinearDartsWrapper   223.226853
                           NoSelection         LinearDartsWrapper   245.507646
                           SingleChronoEpilogi LinearDartsWrapper   240.480503
SynthBase,ip0.0repetition1 CausalPairs         LinearDartsWrapper  1428.773145
                           NoSelection         LinearDartsWrapper   529.315663
                           SingleChronoEpilogi LinearDartsWrapper  1093.818239
SynthBase,ip0.2repetition0 CausalPairs         LinearDartsWrapper   235.665780
                           NoSelection         LinearDartsWrapper   311.790460
                           SingleChronoEpilogi LinearDartsWrapper   281.546331
SynthBase,ip0.2repetition1 CausalPairs         LinearDartsWrapper   498.957450
                           NoSelection         LinearDartsWrapper   875.005650
                           SingleChronoEpilogi LinearDartsWrapper   772.376453
SynthBase,ip0.4repetition0 CausalPairs         LinearDartsWrapper   243.664076
                           NoSelection         LinearDartsWrapper   410.954489
                           SingleChronoEpilogi LinearDartsWrapper   288.146699
